"""
/***************************************************************************
 newMapView
                                 A QGIS plugin
 Abre um novo "Map View" com as camadas selecionadas.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-03-18
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Cardoso
        email                : cardoso.lara@eb.mil.br
 ***************************************************************************/
/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/"""

from qgis.utils import iface
from qgis import gui, core
from qgis.PyQt import QtWidgets
import math
from SAP_Operador.modules.qgis.mapFunctions.mapFunction import MapFunction

class CreateNewMapView(MapFunction):

    def __init__(self):
        super(CreateNewMapView, self).__init__()
    
    def createTheme(self):
        layers = iface.layerTreeView().selectedLayers()
        themeCollection = core.QgsProject.instance().mapThemeCollection()
        themeName = "{0}{1}".format(
            layers[0].name() if len(layers) == 1 else 'tema_misto',
            '' if len(themeCollection.mapThemes()) == 0 else len(themeCollection.mapThemes())
        )
        root = core.QgsProject().instance().layerTreeRoot().clone()
        root.clear()
        [ root.insertLayer(idx, layer) for idx, layer in enumerate(layers)]
        model = core.QgsLayerTreeModel(root)
        themeCollection.insert(themeName, core.QgsMapThemeCollection.createThemeFromCurrentState(root, model))
        return themeName

    def openMapView(self):
        for action in iface.viewMenu().actions():
            if action.objectName() == 'mActionNewMapCanvas':
                action.trigger()
                return True
        return False

    def getMapViewDocks(self):
        """Docks de "Map View" existentes. QgsMapCanvasDockWidget nao e exposta ao
        Python, entao identifica pelo nome da classe C++ ou pelo objectName."""
        docks = []
        for widget in iface.mainWindow().findChildren(QtWidgets.QDockWidget):
            className = widget.metaObject().className()
            if (
                className == 'QgsMapCanvasDockWidget'
                or widget.objectName() == 'QgsMapCanvasDockWidgetBase'
            ):
                docks.append(widget)
        return docks

    def getNewMapView(self, docksBefore):
        """Retorna o dock criado apos openMapView (ausente em docksBefore)."""
        newDocks = [d for d in self.getMapViewDocks() if d not in docksBefore]
        if not newDocks:
            return None
        return newDocks[-1]

    def settings(self, mapView, themeName):
        canvas = mapView.findChild(gui.QgsMapCanvas)
        if canvas is None:
            raise Exception('Canvas do novo mapa nao encontrado')
        canvas.setTheme(themeName)
        try:
            # Sincronizacao de extensao/escala: depende do layout interno do dock
            menuSettings = mapView.findChildren(QtWidgets.QToolButton)[5].menu()
            widgets = menuSettings.actions()[0].defaultWidget().children()
            widgets[1].click()
            widgets[-3].setChecked(True)
            widgets[-1].setValue(1)
        except (IndexError, AttributeError) as e:
            core.QgsMessageLog.logMessage(
                'Nao foi possivel sincronizar o novo mapa: {0}'.format(e),
                'SAP Operador',
                core.Qgis.MessageLevel.Warning
            )

    def run(self):
        layers = iface.layerTreeView().selectedLayers()
        if not layers:
            return (False, 'Selecione ao menos uma camada')
        docksBefore = self.getMapViewDocks()
        if not self.openMapView():
            return (False, 'Falha ao criar novo mapa')
        mapView = self.getNewMapView(docksBefore)
        if mapView is None:
            return (False, 'Falha ao localizar o novo mapa')
        themeName = self.createTheme()
        self.settings(mapView, themeName)
        return (True, '')
